/*
 * Generated by ISE 25.02.9.8732 - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F286_6247();
extern void F288_6409();
extern void F286_6251();
extern void F289_6413();
extern void F291_6577();
extern void F289_6418();
extern void F378_4094();
extern void F354_6093();
extern void F157_1798();
extern EIF_REFERENCE F157_1785();
extern EIF_BOOLEAN F157_1797();
extern EIF_BOOLEAN F157_1805();
extern void F157_1807();
extern void F157_1808();
extern void F157_1809();
extern void F98_1456();
extern EIF_TYPED_VALUE F98_1457();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F286_6247;
	egc_immstr8make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F286_6251;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F289_6413;
	egc_immstr32make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F289_6418;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F378_4094;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F288_6409;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F291_6577;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F354_6093;
	egc_is_scoop_capable = 0;
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F157_1798;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F157_1797;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F157_1785;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F157_1805;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F157_1807;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F157_1808;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F157_1809;

	egc_str_dtype = 287;

	egc_immstr8_dtype = 286;

	egc_str32_dtype = 290;

	egc_immstr32_dtype = 289;
	egc_arr_dtype = 377;
	egc_tup_dtype = 239;
	egc_disp_rout_id = 2399;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x028E;
	egc_sp_wchar = 0x01CF;
	egc_sp_bool = 0x039C;
	egc_sp_uint8 = 0x0378;
	egc_sp_uint16 = 0x0354;
	egc_sp_uint32 = 0x0224;
	egc_sp_uint64 = 0x01EB;
	egc_sp_int8 = 0x030C;
	egc_sp_int16 = 0x02E8;
	egc_sp_int32 = 0x019A;
	egc_sp_int64 = 0x0330;
	egc_sp_real32 = 0x02A0;
	egc_sp_real64 = 0x02C4;
	egc_sp_pointer = 0x024B;
	egc_sp_ref = 0x0178;

	egc_uint8_dtype = 262;
	egc_uint16_dtype = 259;
	egc_uint32_dtype = 256;
	egc_uint64_dtype = 253;
	egc_int8_dtype = 250;
	egc_int16_dtype = 247;
	egc_int32_dtype = 244;
	egc_int64_dtype = 241;
	egc_bool_dtype = 277;
	egc_real32_dtype = 265;
	egc_char_dtype = 274;
	egc_wchar_dtype = 271;
	egc_real64_dtype = 268;
	egc_point_dtype = 280;

	egc_exception_dtype = 116;
	egc_except_emnger_dtype = 156;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "simple_alpine";
	egc_system_location = "D:\\prod\\simple_alpine\\EIFGENs\\simple_alpine_tests\\W_code";
	egc_compiler_tag = 39;
	egc_project_version = 1764806484;
	egc_has_old_special_semantic = 0;
	scount = 1012;

	egc_rcount = 3;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "APPLICATION.make";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 698;
	egc_rcarg[0] = 0;
	
	egc_rlist[1] = "EQA_EVALUATOR.make";
	egc_rcdt[1] = 0;
	egc_rcrid[1] = 2970;
	egc_rcarg[1] = 0;
	
	egc_rlist[2] = "ITP_INTERPRETER.execute";
	egc_rcdt[2] = 0;
	egc_rcrid[2] = 5325;
	egc_rcarg[2] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 97;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F98_1456;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F98_1457;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 25; /* APPLICATION */
	}if (egc_rcdt[1] == 0) {
		egc_rcdt[1] = 210; /* EQA_EVALUATOR */
	}if (egc_rcdt[2] == 0) {
		egc_rcdt[2] = 308; /* ITP_INTERPRETER */
	}
}

#ifdef __cplusplus
}
#endif
